
import React from "react";
import Slider from "../../components/Slider/Slider";
import MarqueeBanner from "../../components/MarqueeBanner";
import ImgTxtSection from "../../components/ImgTxtSection";
import SectionBlock from "../../components/SectionBlock";
import WhyUsLink from "./components/WhyUsLink";
import Services from "../Home/services/services";

import FreeQuoteButton from "../../components/FreeQuoteButton";

const sectionsData = [
  {
    id: 1,
    title: "Traditional Outdoor Kitchen",
    description:
      "Timeless aesthetics, robust construction, and natural finishes.",
    backgroundImage: "assets/images/Products/OutdoorKitchen/Modern/10.webp",
  },
];

const backgroundImage = "assets/images/Products/OutdoorKitchen/Traditional/07.webp";

// Generación dinámica de imágenes
const generateImagePaths = (path: string, count: number) =>
  Array.from({ length: count }, (_, i) => `${path}/${(i + 1).toString().padStart(2, "0")}.webp`);

const imagesTraditional = generateImagePaths("assets/images/Products/OutdoorKitchen/Traditional", 11);

const OutdoorKitchenTraditional: React.FC = () => {
  return (
    <section className="min-h-screen flex flex-col items-center bg-gray-100" aria-labelledby="outdoor-kitchen-heading">

      <SectionBlock sections={sectionsData} />

      <MarqueeBanner />

      {[
        { title: "Traditional Style", images: imagesTraditional },
      ].map((section, index) => (
        <div key={index} className="w-full">
          <h2 className="text-4xl font-semibold my-5 text-center">{section.title}</h2>
          <Slider images={section.images} withBorderT withBorderB />
        </div>
      ))}

      <div className="pt-8 px-5">
        <h2 className="font-semibold text-3xl mb-3">Why should a Traditional Outdoor Kitchen be considered?</h2>
        <div className="ml-1 w-16 h-[3px] bg-[#0d4754] mt-3 mb-2 rounded-full"></div>
        <ul className="list-disc pl-6 text-lg">
          <li>A cozy space perfect for family gatherings is added.</li>
          <li>Designed to last for decades without losing character.</li>
          <li>Is an outdoor design sought that feels authentic and unique, reflecting an appreciation for craftsmanship?</li>
          <li>It is perfectly adapted to classic architectural styles.</li>
        </ul>
      </div>

      {/* Beneficios de Outdoor Kitchen */}
      <div className="flex flex-col my-10 gap-10 items-center">
        <div className="flex flex-col items-center">
          <h2 className="font-semibold text-4xl text-center">Key Features</h2>
          <div className="w-16 h-[3px] bg-[#0d4754] rounded-full mt-4"></div>
        </div>

        {[
          {
            title: "Creation of Cozy Atmospheres for Memorable Gatherings",
            text: "A warm and homely atmosphere is generated by construction with solid brick or natural stone. These materials are ideal for creating a focal point for barbecues, wood-fired pizzas, and significant social events.",
            imageUrl: "assets/images/Products/OutdoorKitchen/Traditional/05.webp",
            imagePosition: "right" as const,
          },
          {
            title: "Proven Durability Against Weather and Demanding Climates",
            text: "Materials such as natural stone or solid brick are used, which effectively resist the inclement weather of the Texas climate. This ensures a solid structure and an attractive appearance in the long term with minimal maintenance.",
            imageUrl: "assets/images/Products/OutdoorKitchen/Traditional/02.webp",
            imagePosition: "left" as const,
          },
          {
            title: "Artisanal Beauty that Provides Unique and Personalized Character",
            text: "Each kitchen is custom-built, highlighting natural textures and handmade finishes. The result is a design with its own character, far from standardized solutions, and adapted to individual taste.",
            imageUrl: "assets/images/Products/OutdoorKitchen/Traditional/03.webp",
            imagePosition: "right" as const,
          },
          {
            title: "Perfect Adaptation to Classic Architectural Styles",
            text: "These kitchens visually complement rustic, colonial, or exposed brick homes. The materials are inherently fire-resistant, allowing for the safe installation of wood-fired ovens or charcoal grills.",
            imageUrl: "assets/images/Products/OutdoorKitchen/Traditional/09.webp",
            imagePosition: "left" as const,
          },
        ].map((section, index) => (
          <ImgTxtSection key={index} {...section} />
        ))}

        <FreeQuoteButton />
      </div>

      <WhyUsLink backgroundImage={backgroundImage} />
      <Services showQuoteButton={false}/>
    </section>
  );
};

export default OutdoorKitchenTraditional;
